/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 */

@interface CAContext : NSObject {
    void * _impl;
}

@property unsigned long long GPURegistryID;
@property (getter=NS_defaultContentsScale, setter=NS_setDefaultContentsScale:) double NS_defaultContentsScale;
@property (setter=NS_setWindowEventMask:) unsigned long long NS_windowEventMask;
@property (copy) NSString *annotation;
@property BOOL colorMatchUntaggedContent;
@property struct CGColorSpace { }*colorSpace;
@property (nonatomic, readonly) unsigned int commitId;
@property unsigned int commitPriority;
@property (copy) NSString *contentsFormat;
@property (readonly) unsigned int contextId;
@property float desiredDynamicRange;
@property (readonly) unsigned int displayId;
@property unsigned int displayMask;
@property unsigned int displayNumber;
@property unsigned int eventMask;
@property (nonatomic, readonly) CAHostingToken *hostingToken;
@property (retain) CALayer *layer;
@property float level;
@property BOOL occlusionClearsEventShape;
@property (readonly) NSDictionary *options;
@property (copy) NSDictionary *payload;
@property int restrictedHostProcessId;
@property (getter=isSecure) BOOL secure;
@property struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } unobscuredRegionOfInterest;
@property (readonly) BOOL valid;
@property BOOL zombifyOnInvalidate;

// Image: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore

+ (id)allContexts;
+ (BOOL)allowsCGSConnections;
+ (id)contextWithCGSConnection:(unsigned int)arg1 options:(id)arg2;
+ (id)contextWithId:(unsigned int)arg1;
+ (id)createCacheBlock;
+ (id)currentContext;
+ (id)drawInContextBlock;
+ (id)finalizeContextBlock;
+ (id)localContext;
+ (id)localContextWithOptions:(id)arg1;
+ (id)objectForSlot:(unsigned int)arg1;
+ (id)remoteContext;
+ (id)remoteContextWithOptions:(id)arg1;
+ (void)setAllowsCGSConnections:(BOOL)arg1;
+ (void)setClientPort:(unsigned int)arg1;
+ (void)setCreateCacheBlock:(id)arg1;
+ (void)setDrawInContextBlock:(id)arg1;
+ (void)setFinalizeContextBlock:(id)arg1;

- (unsigned long long)GPURegistryID;
- (BOOL)addFence:(id)arg1;
- (BOOL)addFence:(id)arg1 completion:(id)arg2;
- (BOOL)addFence:(id)arg1 completionHandler:(id)arg2;
- (id)annotation;
- (BOOL)colorMatchUntaggedContent;
- (struct CGColorSpace { }*)colorSpace;
- (unsigned int)commitId;
- (unsigned int)commitPriority;
- (id)contentsFormat;
- (unsigned int)contextId;
- (void*)contextImpl;
- (unsigned int)createFencePort;
- (unsigned int)createImageSlot:(struct CGSize { double x1; double x2; })arg1 hasAlpha:(BOOL)arg2;
- (unsigned int)createImageSlot:(struct CGSize { double x1; double x2; })arg1 hasAlpha:(BOOL)arg2 extendedColors:(BOOL)arg3;
- (unsigned int)createSlot;
- (void)dealloc;
- (id)debugDescription;
- (void)deleteSlot:(unsigned int)arg1;
- (float)desiredDynamicRange;
- (unsigned int)displayId;
- (unsigned int)displayMask;
- (unsigned int)displayNumber;
- (unsigned int)eventMask;
- (unsigned int)hitTestContext:(struct CGPoint { double x1; double x2; })arg1;
- (id)hostingToken;
- (id)initRemoteWithOptions:(id)arg1;
- (id)initWithCGSConnection:(unsigned int)arg1 options:(id)arg2;
- (id)initWithOptions:(id)arg1 localContext:(bool)arg2;
- (void)invalidate;
- (void)invalidateFences;
- (BOOL)isSecure;
- (id)layer;
- (float)level;
- (BOOL)occlusionClearsEventShape;
- (id)options;
- (void)orderAbove:(unsigned int)arg1;
- (void)orderBelow:(unsigned int)arg1;
- (id)payload;
- (void*)renderContext;
- (void)requestClientGlitch:(double)arg1;
- (void)requestServerGlitch:(double)arg1;
- (int)restrictedHostProcessId;
- (void*)retainRenderContext;
- (void)setAnnotation:(id)arg1;
- (void)setColorMatchUntaggedContent:(BOOL)arg1;
- (void)setColorSpace:(struct CGColorSpace { }*)arg1;
- (void)setCommitPriority:(unsigned int)arg1;
- (void)setContentsFormat:(id)arg1;
- (void)setDesiredDynamicRange:(float)arg1;
- (void)setDisplayMask:(unsigned int)arg1;
- (void)setDisplayNumber:(unsigned int)arg1;
- (void)setEventMask:(unsigned int)arg1;
- (void)setFence:(unsigned int)arg1 count:(unsigned int)arg2;
- (void)setFencePort:(unsigned int)arg1;
- (void)setFencePort:(unsigned int)arg1 commitHandler:(id)arg2;
- (void)setGPURegistryID:(unsigned long long)arg1;
- (void)setLayer:(id)arg1;
- (void)setLevel:(float)arg1;
- (void)setObject:(id)arg1 forSlot:(unsigned int)arg2;
- (void)setOcclusionClearsEventShape:(BOOL)arg1;
- (void)setPayload:(id)arg1;
- (void)setRestrictedHostProcessId:(int)arg1;
- (void)setSecure:(BOOL)arg1;
- (void)setUnobscuredRegionOfInterest:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setZombifyOnInvalidate:(BOOL)arg1;
- (void)transferSlot:(unsigned int)arg1 toContextWithId:(unsigned int)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })unobscuredRegionOfInterest;
- (BOOL)valid;
- (BOOL)waitForCommitId:(unsigned int)arg1 timeout:(double)arg2;
- (BOOL)waitForRenderingWithTimeout:(double)arg1;
- (BOOL)zombifyOnInvalidate;

// Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

// CAContext (NSDefaultContentsScale)

- (double)NS_defaultContentsScale;
- (void)NS_setDefaultContentsScale:(double)arg1;

// CAContext (NSEvent)

- (void)NS_setWindowEventMask:(unsigned long long)arg1;
- (unsigned long long)NS_windowEventMask;

// CAContext (NSFunctionRow)

+ (id)NS_functionRowContext;

// Image: /System/Library/PrivateFrameworks/UIKitServices.framework/Versions/A/UIKitServices

// CAContext (CAContext_ServiceSecurity)

- (void)_notifyIfChangedFromSecure:(BOOL)arg1;

@end
