/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 */

@interface CALayerHost : CALayer {
    BOOL  _asynchronousOpaque;
    float  _asynchronousRenderMaxAPL;
    float  _asynchronousRenderMaxAPLStrength;
    double  _asynchronousRenderPeriod;
    NSArray * _asynchronousRenderTimes;
    BOOL  _rendersAsynchronously;
    BOOL  _tokenNeedsPort;
}

@property BOOL asynchronousOpaque;
@property float asynchronousRenderMaxAPL;
@property float asynchronousRenderMaxAPLStrength;
@property double asynchronousRenderPeriod;
@property (copy) NSArray *asynchronousRenderTimes;
@property unsigned int contextId;
@property (nonatomic, retain) CAHostingToken *hostingToken;
@property BOOL inheritsSecurity;
@property BOOL preservesFlip;
@property BOOL rendersAsynchronously;
@property BOOL resizesHostedContext;
@property BOOL sequestered;
@property BOOL stopsHitTestTransformAccumulation;
@property BOOL stopsSecureSuperlayersValidation;
@property BOOL transformsToScreenSpace;
@property (copy) NSString *zombificationMode;

+ (BOOL)CA_automaticallyNotifiesObservers:(Class)arg1;
+ (BOOL)_hasRenderLayerSubclass;
+ (id)allLayerHosts;
+ (id)defaultValueForKey:(id)arg1;

- (void*)_copyRenderLayer:(void*)arg1 layerFlags:(unsigned int)arg2 commitFlags:(unsigned int*)arg3;
- (bool)_renderLayerDefinesProperty:(unsigned int)arg1;
- (BOOL)asynchronousOpaque;
- (float)asynchronousRenderMaxAPL;
- (float)asynchronousRenderMaxAPLStrength;
- (double)asynchronousRenderPeriod;
- (id)asynchronousRenderTimes;
- (unsigned int)contextId;
- (void)dealloc;
- (void)didChangeValueForKey:(id)arg1;
- (id)hostingToken;
- (BOOL)inheritsSecurity;
- (id)init;
- (void)layerDidBecomeVisible:(BOOL)arg1;
- (BOOL)preservesFlip;
- (BOOL)rendersAsynchronously;
- (BOOL)resizesHostedContext;
- (BOOL)sequestered;
- (void)setAsynchronousOpaque:(BOOL)arg1;
- (void)setAsynchronousRenderMaxAPL:(float)arg1;
- (void)setAsynchronousRenderMaxAPLStrength:(float)arg1;
- (void)setAsynchronousRenderPeriod:(double)arg1;
- (void)setAsynchronousRenderTimes:(id)arg1;
- (void)setContextId:(unsigned int)arg1;
- (void)setHostingToken:(id)arg1;
- (void)setInheritsSecurity:(BOOL)arg1;
- (void)setNeedsAuthoritativeHostingToken;
- (void)setPreservesFlip:(BOOL)arg1;
- (void)setRendersAsynchronously:(BOOL)arg1;
- (void)setResizesHostedContext:(BOOL)arg1;
- (void)setSequestered:(BOOL)arg1;
- (void)setStopsHitTestTransformAccumulation:(BOOL)arg1;
- (void)setStopsSecureSuperlayersValidation:(BOOL)arg1;
- (void)setTransformsToScreenSpace:(BOOL)arg1;
- (void)setZombificationMode:(id)arg1;
- (BOOL)shouldArchiveValueForKey:(id)arg1;
- (BOOL)stopsHitTestTransformAccumulation;
- (BOOL)stopsSecureSuperlayersValidation;
- (BOOL)transformsToScreenSpace;
- (id)zombificationMode;

@end
